Fix typo

diff --git a/github-download-release b/github-download-release
--- a/github-download-release
+++ b/github-download-release
@@ -68,10 +68,10 @@ if [[ "$release" != "latest" ]]; then
 	release="tags/$release"
 fi
 
-command -v curl >/dev/null || { echo "$name: curl: command not found"; \
+command -v curl >/dev/null || { echo "$self: curl: command not found"; \
  exit 1; }
 
-command -v wget >/dev/null || { echo "$name: wget: command not found"; \
+command -v wget >/dev/null || { echo "$self: wget: command not found"; \
  exit 1; }
 
 browser_download_url=$(curl -s "https://api.github.com/repos/$project/releases/$release" \
